# Generated by Django 4.1.2 on 2022-10-07 19:54

import cpu_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CpuInfoSlice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "utilization_percent",
                    models.FloatField(
                        validators=[cpu_info.models.validate_percent_min_max]
                    ),
                ),
            ],
        ),
    ]
